### ISSUE TITLE
Koriolis.Zipstream imported but not always used

### ISSUE THREAD

**Issue by Hezkore** [markcwm/openb3dmax.help#1]
`standard/lightmap.bmx`, `load_3ds.bmx` and `load_b3d.bmx` all import `Koriolis.Zipstream` doesn't always use it.

_(bonus: `Strict` is declared after `Framework` in a lot of examples, which is not okay in BmxNG)_

**Comment by markcwm** [comment]
Thanks, will try to get a fix out for that asap.

**Comment by markcwm** [comment]
Okay, strict after framework error should be fixed in latest 4f30e7f938751cfbc2eee7d5c3ac388051aaa537. Also added is a constraints (basic physics) with cubes example.

Those zipstream examples are fine though as you're meant to change the variable "loader" to test different models and the additional use of streams.

**Comment by Hezkore** [comment]
zipstream isn't used by default though, and so zipstream shouldn't be imported by default imo.
I don't even have zipstream so I just assumed I couldn't try the examples, until I read through the examples and noticed that zipstream wasn't actually used.
If anything the zipstream example should be its own thing.

**Comment by markcwm** [comment]
Oh I see what you mean, yes your suggestion is an improvement thanks. I've split the streams examples in latest 5a2c2f719d41ffe167ac4b0958415f2b1e5bc83c so the default doesn't depend on koriolis.
